 CLASS z_test_bookstore_yk DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC
  FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS z_test_bookstore_yk IMPLEMENTATION.
 ENDCLASS.
